Phoenix Temp 2/Models/jual.cs
namespace Phoenix_Temp_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("jual")]
    public partial class jual
    {
        [Key]
        
        public int id_jual { get; set; }

        [Required]
        
        public string username { get; set; }

        [Required]
        [StringLength(5)]
        public string useradmin { get; set; }

        public int id_barang { get; set; }

        

        [Column(TypeName = "date")]
        public DateTime tgl_beli { get; set; }

        [Range(0, 100,
       ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public int qty { get; set; }

       

        public virtual Barang Barang { get; set; }

        
    }
}

Phoenix Temp 2/Controllers/JualController.cs
using Phoenix_Temp_2.DAL;
using Phoenix_Temp_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phoenix_Temp_2.Controllers
{
    public class JualController : Controller
    {
        // GET: Jual
        private PhoenixModel db = new PhoenixModel();
        public ActionResult Index()
        {
            if (Session["username"] == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    Session["username"] = User.Identity.Name;
                }
                else
                {
                    Response.Redirect("~/Login.aspx");
                }
            }
            using (JualDAL scService = new JualDAL())
            {
                string username =
                    Session["username"] != null ? Session["username"].ToString() : string.Empty;
                return View(scService.GetAllDatabyUser(username).ToList());
            }
        }

        public ActionResult IndexAdmin()
        {
            using (JualDAL scService = new JualDAL())
            {
                var result = scService.GetAllData().ToList();
                return View(result);
            }
        }

        public ActionResult Edit(int id)
        {
            using (JualDAL services = new JualDAL())
            {
                var result = services.GetDataById(id);
                return View(result);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(jual jual)
        {
            using (JualDAL services = new JualDAL())
            {
                try
                {
                    services.Edit(jual);
                    TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                        "success", "Data Shopping Category " + jual.Barang.nama_barang + " berhasil diedit");
                }
                catch (Exception ex)
                {
                    TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                                         "danger", ex.Message);
                }
            }
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("IndexAdmin");
            }
            return RedirectToAction("Index");
        }

        public Barang GetBarangById(int id)

        {

            var result = (from b in db.Barangs

                          where b.id_barang == id

                          select b).SingleOrDefault();

            return result;

        }

        [Authorize]
        public ActionResult AddToCart(int id)
        {
            //cek apakah user sudah login
            if (Session["username"] == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    Session["username"] = User.Identity.Name;
                }
                else
                {
                    Response.Redirect("~/Login.aspx");
                }
            }
            var stock = GetBarangById(id);
            if (stock.stok == 0)
            {
                TempData["Pesan"] = Helpers.Message.GetPesan("Sold Out",
                            "danger", "Item is out of stock");

                return RedirectToAction("Index","Barang", new { area = "" });
            }
            else
            {
                using (JualDAL scService = new JualDAL())
                {

                    var newShoppingCart = new jual
                    {
                        username = Session["username"].ToString(),
                        useradmin = "Admin",
                        qty = 1,
                        id_barang = id,
                        tgl_beli = DateTime.Now
                    };
                    scService.AddToCart(newShoppingCart);
                }

                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int? id, int qty)
        {
            if (id != null)
            {
                using (JualDAL service = new JualDAL())
                {
                    try
                    {
                        service.Delete(id.Value, qty);
                        TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                            "success", "Data kategori berhasil di hapus !");
                    }
                    catch (Exception ex)
                    {
                        TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                        "danger", ex.Message);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAdmin(int? id, int qty)
        {
            if (id != null)
            {
                using (JualDAL service = new JualDAL())
                {
                    try
                    {
                        service.Delete(id.Value, qty);
                        TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                            "success", "Data kategori berhasil di hapus !");
                    }
                    catch (Exception ex)
                    {
                        TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                        "danger", ex.Message);
                    }
                }
            }
            return RedirectToAction("IndexAdmin");
        }
    }
}

Phoenix Temp 2/Views/Jual/AddToCart.cshtml
@model IEnumerable<Phoenix_Temp_2.Models.jual>

@{
    ViewBag.Title = "AddToCart";
}

<h2>AddToCart</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.useradmin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.id_barang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tgl_beli)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.qty)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.useradmin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_barang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tgl_beli)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.qty)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_jual }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_jual }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_jual })
        </td>
    </tr>
}

</table>

Phoenix Temp 2/Views/Jual/Edit.cshtml
@model Phoenix_Temp_2.Models.jual

@{
    ViewBag.Title = "Edit";
}
<div class="container body-content">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id_jual)

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.username)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.useradmin)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id_barang)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.tgl_beli)






            <div class="form-group">
                @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Phoenix Temp 2/Views/Jual/Index.cshtml
@model IEnumerable<Phoenix_Temp_2.Models.jual>

@{
    ViewBag.Title = "Index";
}
<div class="container body-content">
    @Html.Raw(TempData["Pesan"])
    <div style="padding-left:460px">
        <h2>Shopping Cart</h2>
        <div style="text-align:left;padding-left:0px">
           
        </div>
    </div>
    <br />


    <table class="table">
        <tr>
            <th>
                User Name
            </th>

            <th>
                Item Name
            </th>
            <th>
                Buy Date
            </th>
            <th>Price</th>
            <th>
                Quantity
            </th>
            <th>Subtotal</th>
            <th></th>
        </tr>
        @{  decimal total = 0;}
        @foreach (var item in Model)
        {
            var price = string.Format("{0:N0}", item.Barang.harga);
            var subtotal = item.qty * item.Barang.harga;
            var tgl = item.tgl_beli.ToString("d-MMMM-yyyy");

            total += subtotal;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.username)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Barang.nama_barang)
                </td>
                <td>
                    @tgl
                </td>
                <td>@price</td>
                <td>
                    @Html.DisplayFor(modelItem => item.qty)
                </td>
                <td>@string.Format("{0:N0}", subtotal)</td>
                <td>
                    <input type="button" value="Edit" onclick="location.href='@Url.Action("Edit", "Jual")?id=' + @item.id_jual" class="btn btn-warning" />
                    @*<input type="button" value="Delete" onclick="location.href='@Url.Action("Delete", "Jual")?id=' + @item.id_jual" class="btn btn-danger" />*@
                    @Html.ActionLink("Delete", "Delete", "Jual", new { id = @item.id_jual, @item.qty }, new {  @class = "btn btn-danger" })
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Total Order : </td>
            
            <td>@string.Format("{0:N0}", total)</td>
        </tr>

    </table>
    <div style="text-align:center;border:1px solid white">
        <h3 style="text-align:center">Pembayaran</h3>
        <p>Terimakasih telah memesan barang di Phoenix Store</p>
        <p>Pembayaran hanya dapat dilakukan di toko Phoenix Store Jl.Godean no.15, Godean, Yogyakarta</p>
        <p>Konfirmasi pemesanan dengan menggunakan Username dan Tanggal Pemesanan di toko Phoenix Store</p>
    </div>
    <br />
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Barang")';return false;"> << Buy More</button>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Index", "Home")';return false;">Done</button>
</div>

Phoenix Temp 2/Views/Jual/IndexAdmin.cshtml
@model IEnumerable<Phoenix_Temp_2.Models.jual>

@{
    ViewBag.Title = "IndexAdmin";
}
<div class="container body-content">
    <h2>IndexAdmin</h2>

   
    <table class="table">
        <tr>
            <th>
                User Name
            </th>

            <th>
                Nama Barang
            </th>
            <th>
                Tanggal Beli
            </th>
            <th>Harga</th>
            <th>
                Quantity
            </th>
            <th>Subtotal</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            var price = string.Format("{0:N0}", item.Barang.harga);
            var subtotal = item.qty * item.Barang.harga;
            var tgl = item.tgl_beli.ToString("d-MMMM-yyyy");


            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.username)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Barang.nama_barang)
                </td>
                <td>
                    @tgl
                </td>
                <td>@price</td>
                <td>
                    @Html.DisplayFor(modelItem => item.qty)
                </td>
                <td>@string.Format("{0:N0}", subtotal)</td>
                <td>
                    <input type="button" value="Edit" onclick="location.href='@Url.Action("Edit", "Jual")?id=' + @item.id_jual" class="btn btn-warning" />
                    <input type="button" value="Delete" onclick="location.href='@Url.Action("DeleteAdmin", "Jual")?id=' + @item.id_jual + '&qty=' + @item.qty" class="btn btn-danger" />
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>

        </tr>

    </table>
</div>