Phoenix Temp 2/Controllers/BarangController.cs
using Phoenix_Temp_2.DAL;
using Phoenix_Temp_2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phoenix_Temp_2.Controllers
{
    public class BarangController : Controller
    {
        // GET: Barang
        public ActionResult Index()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetData().ToList();
                return View(result);
            }
        }

        public ActionResult IndexRaket()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetRaket().ToList();
                return View(result);
            }
        }
        public ActionResult IndexKok()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetKok().ToList();
                return View(result);
            }
        }
        public ActionResult IndexBaju()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetBaju().ToList();
                return View(result);
            }
        }
        public ActionResult IndexCelana()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetCelana().ToList();
                return View(result);
            }
        }
        public ActionResult IndexSepatu()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetSepatu().ToList();
                return View(result);
            }
        }
        public ActionResult IndexAksesoris()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetAksesoris().ToList();
                return View(result);
            }
        }

        public ActionResult IndexDiskon()
        {
            using (BarangDAL svbarang = new BarangDAL())
            {
                var result = svbarang.GetDiskon().ToList();
                return View(result);
            }
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Create(Barang barang, HttpPostedFileBase uploadimage)
        {
            string filePath = "";
            if (uploadimage.ContentLength > 0)
            {
                string fileName = Guid.NewGuid().ToString() + "_" + uploadimage.FileName;
                filePath = Path.Combine(HttpContext.Server.MapPath("~/Content/Images"), fileName);
                uploadimage.SaveAs(filePath);
                barang.gbr_barang = fileName;
            }


            using (BarangDAL svBrg = new BarangDAL())
            {
                try
                {
                    svBrg.Add(barang);
                    TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                      "success", "Data Barang " + barang.nama_barang + " berhasil ditambah");
                }
                catch (Exception ex)
                {
                    TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                                          "danger", ex.Message);
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            using (BarangDAL services = new BarangDAL())
            {
                var result = services.GetDataById(id);
                return View(result);
            }
        }

        public ActionResult Search(string txtSearch)
        {
            using (BarangDAL svCat = new BarangDAL())
            {
                var results = svCat.Search(txtSearch).ToList();
                TempData["Pesan"] = Helpers.Message.GetPesan(" ",
                      "warning", "Anda mencari " + txtSearch );
                return View(results);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Barang brg)
        {
            
            
            
            
            using (BarangDAL services = new BarangDAL())
            {
                try
                {
                    services.Edit(brg);
                    TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                        "success", "Data barang " + brg.nama_barang + " berhasil diedit");
                }
                catch (Exception ex)
                {
                    TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                                         "danger", ex.Message);
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                using (BarangDAL service = new BarangDAL())
                {
                    try
                    {
                        service.Delete(id.Value);
                        TempData["Pesan"] = Helpers.Message.GetPesan("Sukses !",
                            "success", "Data buku berhasil didelete !");
                    }
                    catch (Exception ex)
                    {
                        TempData["Pesan"] = Helpers.Message.GetPesan("Error !",
                                             "danger", ex.Message);
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Phoenix Temp 2/Views/Shared/_Layout.cshtml
@using MvcSiteMapProvider.Web.Html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Badminton Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/hover.css" rel="stylesheet" media="all">
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />

    <script>
        $(document).ready(function () {
            // Add smooth scrolling to all links in navbar + footer link
            $(".navbar a, footer a[href='#myPage']").on('click', function (event) {
                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {
                    // Prevent default anchor click behavior
                    event.preventDefault();
                    // Store hash
                    var hash = this.hash;
                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 900, function () {
                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                } // End if
            });
        })
    </script>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar">

    <div class="navbar navbar-inverse navbar-fixed-top" style="height:70px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div style="padding-left:70px;padding-top:15px">
                    @*@Html.ActionLink("PHOENIX", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                    <a href='@Url.Action("Index","Home")'><img src="~/Content/Images/phoenix.png" height="43" width="100" /></a>
                </div>
            </div>
            <div style="padding-top:10px">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse " style="position:relative;top:19px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div id="navmenu" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                   
                    <li class="hvr-bounce-to-top">@Html.ActionLink("Home", "Index", "Home",  routeValues: null, htmlAttributes: new { @style = "color:white" })</li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>

                    <li class="dropdown hvr-bounce-to-top" style="padding-left:0px">
                        <a href="#"  class="dropdown" data-toggle="dropdown" role="button" aria-expanded="false" style="color:white">Items &nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" id="myItem" style="padding-left:0px">
                            <li style="padding-left:0px">
                                <a href="@Url.Action("IndexRaket","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-tree-conifer"></span> Raket
                                </a>
                               
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="@Url.Action("IndexKok","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-tree-conifer"></span> Kok
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="@Url.Action("IndexBaju","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-cloud"></span> Baju
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="@Url.Action("IndexCelana","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-floppy-disk"></span> Celana
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="@Url.Action("IndexSepatu","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-refresh"></span> Sepatu
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="@Url.Action("IndexAksesoris","Barang")" target="_blank">
                                    <span class="glyphicon glyphicon-music"></span> Aksesoris
                                </a>
                            </li>
                            
                        </ul>
                    </li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li class="hvr-bounce-to-top">@Html.ActionLink("Full Catalog", "Index", "Barang", routeValues: null, htmlAttributes : new { @style = "color:white" })</li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li class="hvr-bounce-to-top">@Html.ActionLink("Discount", "IndexDiskon", "Barang", routeValues: null, htmlAttributes: new { @style = "color:white" })</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="kontener body-konten">
        
        @RenderBody()
        <hr />
        <footer style="color:white;margin-left:50px" class="text-center">
            <p class="back-top" style="color:white">
                <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP" style="color:white">
                    <span class="glyphicon glyphicon-chevron-up" style="color:white"></span><br />
                    Back to top
                </a>
            </p>
            <p>&copy; @DateTime.Now.Year - Phoenix Store</p>
            <p>0274 - 488966</p>
            <p>Jl. Godean no.5, Godean, Yogyakarta</p>
            <p><a href="@Url.Action("About","Home")" target="_blank" style="color:white">About Us</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>